[settings]
DEBUG = true
ALLOWED_HOSTS = ['127.0.0.1', 'web']
INTERNAL_IPS = ['127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1']

[smtp]
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "465"
EMAIL_USE_TLS = false
EMAIL_USE_SSL = true

[recaptcha]
RECAPTCHA_DEFAULT_ACTION = 'generic'
RECAPTCHA_SCORE_THRESHOLD = 0.5

[celery]
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASKS_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

[celery.broker_transport_options]
visibility_timeout = 3600
