import os
import toml

from django_blog.settings import BASE_DIR

CONFIG_FILE = 'config.toml'
CONFIG_FILE_PATH = os.path.join(BASE_DIR, CONFIG_FILE)
CONFIG_DATA = toml.load(CONFIG_FILE_PATH)

SECRET_KEY = os.environ['SECRET_KEY']

DEBUG = CONFIG_DATA['settings']['DEBUG']
ALLOWED_HOSTS = CONFIG_DATA['settings']['ALLOWED_HOSTS']
INTERNAL_IPS = CONFIG_DATA['settings']['INTERNAL_IPS']

# SMTP
EMAIL_HOST = CONFIG_DATA['smtp']['EMAIL_HOST']
EMAIL_USE_TLS = CONFIG_DATA['smtp']['EMAIL_USE_TLS']
EMAIL_USE_SSL = CONFIG_DATA['smtp']['EMAIL_USE_SSL']
EMAIL_PORT = CONFIG_DATA['smtp']['EMAIL_PORT']
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']

# POSTGRES
POSTGRES_DB = os.environ['POSTGRES_DB']
POSTGRES_USER = os.environ['POSTGRES_USER']
POSTGRES_PASSWORD = os.environ['POSTGRES_PASSWORD']
POSTGRES_HOST = CONFIG_DATA['db']['POSTGRES_HOST']
POSTGRES_PORT = CONFIG_DATA['db']['POSTGRES_PORT']


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': POSTGRES_HOST,
        'PORT': POSTGRES_PORT,
    }
}


# RECAPTCHA
RECAPTCHA_PUBLIC_KEY = os.environ['RECAPTCHA_PUBLIC_KEY']
RECAPTCHA_PRIVATE_KEY = os.environ['RECAPTCHA_PRIVATE_KEY']
RECAPTCHA_DEFAULT_ACTION = CONFIG_DATA['recaptcha']['RECAPTCHA_DEFAULT_ACTION']
RECAPTCHA_SCORE_THRESHOLD = CONFIG_DATA['recaptcha']['RECAPTCHA_SCORE_THRESHOLD']

# CELERY
REDIS_HOST = os.environ['REDIS_HOST']
REDIS_PORT = os.environ['REDIS_PORT']
REDIS_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'

CELERY_BROKER_TRANSPORT_OPTIONS = CONFIG_DATA['celery']['broker_transport_options']
CELERY_ACCEPT_CONTENT = CONFIG_DATA['celery']['CELERY_ACCEPT_CONTENT']
CELERY_TASKS_SERIALIZER = CONFIG_DATA['celery']['CELERY_TASKS_SERIALIZER']
CELERY_RESULT_SERIALIZER = CONFIG_DATA['celery']['CELERY_RESULT_SERIALIZER']
