# Generated by Django 5.0.1 on 2024-01-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_share'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Share',
            new_name='NetworkModel',
        ),
    ]
