# Generated by Django 5.0.1 on 2024-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отвечено'),
        ),
    ]
