# Generated by Django 5.0.1 on 2024-03-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_contact_options_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
