# Generated by Django 5.0.1 on 2024-08-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_contact'),
        ('user', '0011_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, default='admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.userprofile'),
        ),
    ]
