# Generated by Django 5.0.1 on 2024-01-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_bio_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
