# Generated by Django 5.0.1 on 2024-01-22 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, default='user/img/user_photo.jpg', upload_to='avatars/%Y/%m/%d/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
