# Generated by Django 5.0.1 on 2024-03-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscription',
            options={'verbose_name': 'Email подписка', 'verbose_name_plural': 'Email подписки'},
        ),
    ]
