# Generated by Django 5.0.1 on 2024-03-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_notification', '0002_alter_emailsubscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscription',
            options={'verbose_name': 'Email подписка(у)', 'verbose_name_plural': 'Email подписки'},
        ),
    ]
