# Generated by Django 5.0.1 on 2024-08-20 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notification', '0003_alter_emailsubscription_options'),
        ('user', '0011_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='Пользователь'),
        ),
    ]
